drop database if exists PR12;
create database IF NOT EXISTS PR12;

use PR12;

/* CREACION DE LA TABLA */
CREATE TABLE IF NOT EXISTS PRODUCTOS 
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    PRECIO FLOAT,
    FECHA_CADUCIDAD DATE
);

/* INSERTAR VALORES EN LA TABLA */
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CADUCIDAD) VALUES ('Lechuga',10,DATE '2021/07/27');
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CADUCIDAD) VALUES ('Tomate',15,DATE '2021/12/19');
INSERT INTO PRODUCTOS (NOMBRE,PRECIO,FECHA_CADUCIDAD) VALUES ('Fresa',5,DATE '2022/01/30');
